const customExportFields = [
  {
    title: '基本信息',
    propertyArr: [
      { key: 'orderCode', label: '订单号', checked: true, readonly: true },
      { key: 'refNo', label: '参考单号', checked: true },
      { key: 'ecOrderCode', label: '第三方订单号', checked: true },
      { key: 'bigStatusDesc', label: '状态1', checked: true },
      { key: 'statusDesc', label: '状态2', checked: true },
      { key: 'createTime', label: '创建时间', checked: true },
      { key: 'customerDesc', label: '客户名称', checked: true },
      { key: 'customerTypeDesc', label: '客户类型', checked: true },
      { key: 'creatorName', label: '创建人', checked: true },
      { key: 'auditTime', label: '审核时间', checked: true },
      { key: 'sendTime', label: '发货时间', checked: true },
      { key: 'estimateArriveDate', label: '预计到货时间', checked: true },
      { key: 'signTime', label: '签收时间', checked: true },
      { key: 'operationExpectedArrivalTime', label: '平台送达时间', checked: true },
      { key: 'platformExpectedSendTime', label: '期望发货时间', checked: true },
      { key: 'deliverTypeDesc', label: '交货方式', checked: true },
      { key: 'orderSaleTypeDesc', label: '订单渠道', checked: true },
      { key: 'organizationDeptName', label: '部门', checked: true },
    ],
  },
  {
    title: '收件人信息',
    propertyArr: [
      { key: 'receiverName', label: '收件人', checked: true },
      { key: 'countryCode', label: '国家/地区', checked: true },
      { key: 'province', label: '所在省/州', checked: true },
      { key: 'city', label: '所在城市', checked: true },
      { key: 'area', label: '区/县', checked: true },
      { key: 'address', label: '详细地址1', checked: true },
      { key: 'address2', label: '详细地址2', checked: true },
      { key: 'houseNumber', label: '门牌号', checked: true },
      { key: 'email', label: '邮箱', checked: true },
      { key: 'phone', label: '电话', checked: true },
      { key: 'zipcode', label: '邮编', checked: true },
    ],
  },
  {
    title: '产品信息',
    propertyArr: [
      { key: 'productName', label: '产品名称', checked: true },
      { key: 'skuCode', label: '产品SKU', checked: true },
      { key: 'supplySku', label: '供应链SKU', checked: true },
      { key: 'num', label: '数量（件）', checked: true },
      { key: 'price', label: '销售单价（不含税）', checked: true },
      { key: 'taxPrice', label: '销售单价（含税）', checked: true },
      { key: 'upcCode', label: 'UPC码', checked: true },
      { key: 'eanCode', label: 'EAN码', checked: true },
      { key: 'customerSkuCode', label: '客户SKU编码', checked: true },
      { key: 'productNameEn', label: '客户产品名称（英文）', checked: true },
      { key: 'uniqueCode', label: '客户唯一码', checked: true },
      { key: 'gtin', label: 'GTIN', checked: true },
      { key: 'productLine', label: '品线', checked: true },
      { key: 'productGroup', label: '所属产品组', checked: true },
      { key: 'categoryName', label: '五级分类', checked: true },
      { key: 'suggestPrice', label: '建议售价', checked: true },
      { key: 'postalPrice', label: '报价', checked: true },
      { key: 'taxRateDesc', label: '税率', checked: true },
      { key: 'priceTaxAmount', label: '税额', checked: true },
      { key: 'commission2', label: '佣金', checked: true },
    ],
  },
  {
    title: '物流信息',
    propertyArr: [
      { key: 'deliveryDesc', label: '发货方式', checked: true },
      { key: 'warehouseDesc', label: '发货仓库', checked: true },
      { key: 'shippingDesc', label: '物流渠道', checked: true },
      { key: 'warehouseDeliveryCode', label: '仓配订单号', checked: true },
      { key: 'trackNum', label: '跟踪号', checked: true },
      { key: 'waybillCode', label: '运单号', checked: true },
      { key: 'mark', label: '唛头', checked: true },
      { key: 'thirdOutboundNo', label: '三方仓出库单号', checked: true },
    ],
  },
  {
    title: '结算信息',
    propertyArr: [
      { key: 'paymentTerm', label: '收款条件', checked: true },
      { key: 'settlementMethodDesc', label: '结算方式', checked: true },
      { key: 'settlementPeriodDesc', label: '结算周期', checked: true },
      { key: 'contractSubject', label: '签约主体', checked: true },
    ],
  },
  {
    title: '金额信息',
    propertyArr: [
      { key: 'currencyCode', label: '货币类型', checked: true },
      { key: 'taxAmount', label: '总金额 (含税)', checked: true },
      { key: 'totalAmount', label: '总金额 (不含税)', checked: true },
      { key: 'freightAmount', label: '运费', checked: true },
      { key: 'salesFreightAmount', label: '销售运费', checked: true },
      { key: 'discountAmount', label: '折扣金额', checked: true },
      { key: 'commission', label: '总佣金', checked: true },
      { key: 'taxTransactionAmount', label: '交易额（含税）', checked: true },
      { key: 'transactionAmount', label: '交易额（不含税）', checked: true },
      { key: 'taxRealTransactionAmount', label: '实际交易额（含税）', checked: true },
      { key: 'realTransactionAmount', label: '实际交易额（不含税）', checked: true },
      { key: 'productTaxAmount', label: '总税额', checked: true },
    ],
  },

  {
    title: '备注信息',
    propertyArr: [
      { key: 'customerRemark', label: '客服备注', checked: true },
      { key: 'orderRemark', label: '订单备注', checked: true },
    ],
  },
];
export default customExportFields;
