export default [
  // 预算
  {
    path: '/budget/parameterSet',
    meta: { title: '参数设置' },
    component: () => import('@/views/budget/base/parameterSet/index.vue'),
    name: 'parameterSet',
  },
  {
    path: '/budget/checkoutSet',
    meta: { title: '预算校验设置' },
    component: () => import('@/views/budget/base/checkoutSet/index.vue'),
    name: 'budgetCheckoutSet',
  },
  {
    path: '/budget/budgetSummaryList',
    meta: { title: '预算汇总列表' },
    component: () => import('@/views/budget/budgetSummary/budgetSummaryList/index.vue'),
    name: 'budgetSummaryList',
  },
  {
    path: '/budget/summaryRule',
    meta: { title: '预算汇总规则' },
    component: () => import('@/views/budget/budgetSummary/summaryRule/index.vue'),
    name: 'budgetSummaryRule',
  },
  {
    path: '/budget/summaryRuleAdd',
    meta: { title: '新增预算汇总规则' },
    component: () => import('@/views/budget/budgetSummary/summaryRule/add.vue'),
    name: 'budgetSummaryRuleAdd',
  },
  {
    path: '/budget/summaryRuleEdit',
    meta: { title: '编辑预算汇总规则' },
    component: () => import('@/views/budget/budgetSummary/summaryRule/edit.vue'),
    name: 'budgetSummaryRuleEdit',
  },
  {
    path: '/budget/summaryRuleDetail',
    meta: { title: '预算汇总规则详情' },
    component: () => import('@/views/budget/budgetSummary/summaryRule/detail.vue'),
    name: 'budgetSummaryRuleDetail',
  },
  {
    path: '/budget/product',
    meta: { title: '预算产品信息' },
    component: () => import('@/views/budget/base/product/index.vue'),
    name: 'budgetProduct',
  },
  {
    path: '/budget/SKUSaleTime',
    meta: { title: 'SKU开卖时间' },
    component: () => import('@/views/budget/base/SKUSaleTime/index.vue'),
    name: 'budgetSKUSaleTime',
  },
  {
    path: '/budget/sellingPrice',
    meta: { title: '售价信息' },
    component: () => import('@/views/budget/base/sellingPrice/index.vue'),
    name: 'budgetSellingPrice',
  },
  {
    path: '/budget/purchaseCostPrice',
    meta: { title: '采购成本价' },
    component: () => import('@/views/budget/base/purchaseCostPrice/index.vue'),
    name: 'budgetPurchaseCostPrice',
  },
  {
    path: '/budget/project',
    meta: { title: '研发项目' },
    component: () => import('@/views/budget/base/project/index.vue'),
    name: 'budgetProject',
  },
  {
    path: '/budget/country',
    meta: { title: '国家信息' },
    component: () => import('@/views/budget/base/country/index.vue'),
    name: 'budgetCountry',
  },
  {
    path: '/budget/channel',
    meta: { title: '渠道信息' },
    component: () => import('@/views/budget/base/channel/index.vue'),
    name: 'budgetChannel',
  },
  {
    path: '/budget/exchangeRate',
    meta: { title: '基准汇率' },
    component: () => import('@/views/budget/base/exchangeRate/index.vue'),
    name: 'budgetExchangeRate',
  },
  {
    path: '/budget/consultingProject',
    meta: { title: '咨询项目' },
    component: () => import('@/views/budget/base/consultingProject/index.vue'),
    name: 'budgetConsultingProject',
  },
  {
    path: '/budget/operationalPeople',
    meta: { title: '运营人员信息' },
    component: () => import('@/views/budget/base/operationalPeople/index.vue'),
    name: 'budgetOperationalPeople',
  },
  {
    path: '/budget/GTM',
    meta: { title: 'GTM品线管理' },
    component: () => import('@/views/budget/base/GTM/index.vue'),
    name: 'budgetGTM',
  },
  {
    path: '/budget/sellInUnitPrice',
    meta: { title: 'Sell In单价' },
    component: () => import('@/views/budget/base/sellInUnitPrice/index.vue'),
    name: 'budgetSellInUnitPrice',
  },
  {
    path: '/budget/firstLegUnitPrice',
    meta: { title: '头程单价信息' },
    component: () => import('@/views/budget/base/firstLegUnitPrice/index.vue'),
    name: 'budgetFirstLegUnitPrice',
  },
  {
    path: '/budget/marketingExpenses',
    meta: { title: '营销费用' },
    component: () => import('@/views/budget/base/marketingExpenses/index.vue'),
    name: 'budgetMarketingExpenses',
  },
  {
    path: '/budget/marketingActivitiesList',
    meta: { title: '营销活动清单' },
    component: () => import('@/views/budget/base/marketingActivitiesList/index.vue'),
    name: 'budgetMarketingActivitiesList',
  },
  {
    path: '/budget/dailyExpenses',
    meta: { title: '日常费用' },
    component: () => import('@/views/budget/base/dailyExpenses/index.vue'),
    name: 'budgetDailyExpenses',
  },
  {
    path: '/budget/salesPurchasingPrice',
    meta: { title: '进销存-采购单价' },
    component: () => import('@/views/budget/base/salesPurchasingPrice/index.vue'),
    name: 'budgetSalesPurchasingPrice',
  },
  {
    path: '/budget/assets',
    meta: { title: '资产信息' },
    component: () => import('@/views/budget/base/assets/index.vue'),
    name: 'budgetAssets',
  },
  {
    path: '/budget/budgetPlan',
    meta: { title: '预算方案' },
    component: () => import('@/views/budget/compilation/plan/index.vue'),
    name: 'budgetPlan',
  },
  {
    path: '/budget/budgetCompilationManage',
    meta: { title: '预算编制管理' },
    component: () => import('@/views/budget/compilation/compilationManage/index.vue'),
    name: 'budgetCompilationManage',
  },
  {
    path: '/budget/budgetCompilationPlatform',
    meta: { title: '预算编制台' },
    component: () => import('@/views/budget/compilation/compilationPlatform/index.vue'),
    name: 'budgetCompilationPlatform',
  },
  {
    path: '/budgetTable',
    meta: { title: '预算编制表' },
    component: () => import('@/views/budget/budgetTable/index.vue'),
    name: 'budgetTable',
  },
];
