export default [
  // 财务系统 - 基础信息管理
  {
    path: '/finance/customer',
    meta: { title: '客户管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/customer/index.vue'),
    name: 'financeCustomer',
  },
  {
    path: '/finance/product',
    meta: { title: '产品管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/product/index.vue'),
    name: 'financeProduct',
  },
  {
    path: '/finance/productClass',
    meta: { title: '产品分类管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/productClass/index.vue'),
    name: 'financeProductClass',
  },
  {
    path: '/finance/newProductProject',
    meta: { title: '新品项目', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/newProductProject/index.vue'),
    name: 'newProductProject',
  },
  {
    path: '/finance/SPU',
    meta: { title: 'SPU管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/SPU/index.vue'),
    name: 'financeSPU',
  },
  {
    path: '/finance/customsClearancePlan',
    meta: { title: '报关计划', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/customsClearancePlan/index.vue'),
    name: 'customsClearancePlan',
  },
  {
    path: '/finance/GTM',
    meta: { title: 'GTM品线管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/GTM/index.vue'),
    name: 'financeGTM',
  },
  {
    path: '/finance/GTMMap',
    meta: { title: 'GTM品线映射', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/GTMMap/index.vue'),
    name: 'financeGTMMap',
  },
  {
    path: '/finance/financeWarehouse',
    meta: { title: '仓库管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/warehouse/index.vue'),
    name: 'financeWarehouse',
  },
  // warehouseVatMap
  {
    path: '/finance/warehouseVatMap',
    meta: { title: '仓库VAT管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/warehouseVatMap/index.vue'),
    name: 'warehouseVatMap',
  },
  {
    path: '/finance/supplier',
    meta: { title: '供应商管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/supplier/index.vue'),
    name: 'financeSupplier',
  },
  {
    path: '/finance/financeOtherCompany',
    meta: { title: '其他往来单位', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/otherCompany/index.vue'),
    name: 'financeOtherCompany',
  },
  {
    path: '/finance/preprocessingRule',
    meta: { title: '预处理规则' },
    component: () => import('@/views/finance/basic/preprocessingRule/index.vue'),
    name: 'preprocessingRule',
  },
  {
    path: '/finance/preprocessingRule/add',
    meta: { title: '新增预处理规则', activeMenu: '/finance/preprocessingRule' },
    component: () => import('@/views/finance/basic/preprocessingRule/add.vue'),
    name: 'preprocessingRuleAdd',
  },
  {
    path: '/finance/preprocessingRule/edit',
    meta: { title: '编辑预处理规则', activeMenu: '/finance/preprocessingRule' },
    component: () => import('@/views/finance/basic/preprocessingRule/edit.vue'),
    name: 'preprocessingRuleEdit',
  },
  {
    path: '/finance/preprocessingRule/detail',
    meta: { title: '预处理规则详情', activeMenu: '/finance/preprocessingRule' },
    component: () => import('@/views/finance/basic/preprocessingRule/detail.vue'),
    name: 'preprocessingRuleDetail',
  },
  {
    path: '/finance/department',
    meta: { title: '部门管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/department/index.vue'),
    name: 'financeDepartment',
  },
  {
    path: '/finance/member',
    meta: { title: '员工管理', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/member/index.vue'),
    name: 'financeMember',
  },
  {
    path: '/finance/paymentTerms',
    meta: { title: '收款条件', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/paymentTerms/index.vue'),
    name: 'paymentTerms',
  },
  {
    path: '/finance/bankAccountNumber',
    meta: { title: '银行账号', menuPath: ['基础信息管理', '财务系统'] },
    component: () => import('@/views/finance/basic/bankAccountNumber/index.vue'),
    name: 'bankAccountNumber',
  },
  {
    path: '/finance/OAPaymentBills',
    meta: { title: 'OA付款单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/oaPaymentBills/index.vue'),
    name: 'financeOAPaymentBills',
  },
  {
    path: '/finance/fundAllotBills',
    meta: { title: '资金调拨单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/fundAllotBills/index.vue'),
    name: 'fundAllotBills',
  },
  {
    path: '/finance/lendBills',
    meta: { title: '借款单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/lendBills/index.vue'),
    name: 'lendBills',
  },
  {
    path: '/finance/repaymentBills',
    meta: { title: '还款单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/repaymentBills/index.vue'),
    name: 'repaymentBills',
  },
  {
    path: '/finance/payBills',
    meta: { title: '应付单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/payBills/index.vue'),
    name: 'payBills',
  },
  {
    path: '/finance/payApplyBills',
    meta: { title: '付款申请单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/payApplyBills/index.vue'),
    name: 'payApplyBills',
  },
  {
    path: '/finance/wms/otherBill',
    meta: { title: '其他出入库单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/wms/otherBill/index.vue'),
    name: 'wmsOtherBill',
  },
  {
    path: '/finance/wms/wmsSalesOutStockBill',
    meta: { title: '销售出库单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/wms/salesOutStockBill/index.vue'),
    name: 'wmsSalesOutStockBill',
  },
  {
    path: '/finance/wms/transferBill',
    meta: { title: '调拨单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/wms/transferBill/index.vue'),
    name: 'wmsTransferBill',
  },
  {
    path: '/finance/billInvoiceDifference',
    meta: { title: '对账单与发票差异', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/billInvoiceDifference/index.vue'),
    name: 'billInvoiceDifference',
  },
  {
    path: '/finance/reimbursementBills',
    meta: { title: '报销单', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/reimbursementBills/index.vue'),
    name: 'reimbursementBills',
  },
  {
    path: '/finance/purchaseBillsManagement',
    meta: { title: '采购单据管理', menuPath: ['业务单据', '财务系统'] },
    component: () => import('@/views/finance/bills/purchaseBillsManagement/index.vue'),
    name: 'purchaseBillsManagement',
  },
  {
    path: '/finance/OAInvoiceSearch',
    meta: { title: 'OA发票检索', menuPath: ['税务管理', '财务系统'] },
    component: () => import('@/views/finance/bills/oaInvoiceSearch/index.vue'),
    name: 'financeOAInvoiceSearch',
  },
  {
    path: '/organizationMap',
    meta: { title: '组织映射关系' },
    component: () => import('@/views/finance/organizationMap/index.vue'),
    name: 'organizationMap',
  },
  {
    path: '/shopMap',
    meta: { title: '店铺映射关系' },
    component: () => import('@/views/finance/shopMap/index.vue'),
    name: 'shopMap',
  },
  {
    path: '/incomeRule',
    meta: { title: '收入规则' },
    component: () => import('@/views/finance/income/incomeRule/index.vue'),
    name: 'incomeRule',
  },
  {
    path: '/incomeRule/add',
    meta: { title: '新增收入规则', activeMenu: '/incomeRule' },
    component: () => import('@/views/finance/income/incomeRule/add.vue'),
    name: 'incomeRuleAdd',
  },
  {
    path: '/incomeRule/edit',
    meta: { title: '编辑收入规则', activeMenu: '/incomeRule' },
    component: () => import('@/views/finance/income/incomeRule/edit.vue'),
    name: 'incomeRuleEdit',
  },
  {
    path: '/incomeRule/detail',
    meta: { title: '收入规则详情', activeMenu: '/incomeRule' },
    component: () => import('@/views/finance/income/incomeRule/detail.vue'),
    name: 'incomeRuleDetail',
  },
  {
    path: '/payBackRule',
    meta: { title: '回款规则' },
    component: () => import('@/views/finance/income/payBackRule/index.vue'),
    name: 'payBackRule',
  },
  {
    path: '/payBackRuleRule/add',
    meta: { title: '新增回款规则', activeMenu: '/payBackRule' },
    component: () => import('@/views/finance/income/incomeRule/payBackRuleAdd.vue'),
    name: 'payBackRuleAdd',
  },
  {
    path: '/payBackRule/edit',
    meta: { title: '编辑回款规则', activeMenu: '/payBackRule' },
    component: () => import('@/views/finance/income/incomeRule/edit.vue'),
    name: 'payBackRuleEdit',
  },
  {
    path: '/payBackRule/detail',
    meta: { title: '收款规则详情', activeMenu: '/payBackRule' },
    component: () => import('@/views/finance/income/incomeRule/detail.vue'),
    name: 'payBackRuleDetail',
  },
  {
    path: '/payBackAnalysis',
    meta: { title: '回款解析' },
    component: () => import('@/views/finance/income/payBackAnalysis/index.vue'),
    name: 'payBackAnalysis',
  },
  {
    path: '/payBackStatement',
    meta: { title: 'ToC收款结算单' },
    component: () => import('@/views/finance/income/payBackStatement/index.vue'),
    name: 'payBackStatement',
  },
  {
    path: '/paymentCollection',
    meta: { title: 'ToB收款结算单' },
    component: () => import('@/views/finance/income/paymentCollection/index.vue'),
    name: 'paymentCollection',
  },
  {
    path: '/collectionClaim',
    meta: { title: '收款认领' },
    component: () => import('@/views/finance/income/paymentCollection/detail.vue'),
    name: 'collectionClaim',
  },
  {
    path: '/financeBillsRule',
    meta: { title: '单据取值规则' },
    component: () => import('@/views/finance/income/financeBillsRule/index.vue'),
    name: 'financeBillsRule',
  },
  {
    path: '/financeBillsRule/add',
    meta: { title: '新增单据取值规则', activeMenu: '/financeBillsRule' },
    component: () => import('@/views/finance/income/incomeRule/financeBillsRuleAdd.vue'),
    name: 'financeBillsRuleAdd',
  },
  {
    path: '/financeBillsRule/edit',
    meta: { title: '编辑单据取值规则', activeMenu: '/financeBillsRule' },
    component: () => import('@/views/finance/income/incomeRule/edit.vue'),
    name: 'financeBillsRuleEdit',
  },
  {
    path: '/financeBillsRule/detail',
    meta: { title: '单据取值规则详情', activeMenu: '/financeBillsRule' },
    component: () => import('@/views/finance/income/incomeRule/detail.vue'),
    name: 'financeBillsRuleDetail',
  },
  {
    path: '/financeBillsAnalysis',
    meta: { title: '单据取值解析' },
    component: () => import('@/views/finance/income/financeBillsAnalysis/index.vue'),
    name: 'financeBillsAnalysis',
  },
  {
    path: '/financeBillsStatement',
    meta: { title: '单据推送列表' },
    component: () => import('@/views/finance/income/financeBills/index.vue'),
    name: 'financeBillsStatement',
  },
  {
    path: '/financeBillsStatement/detail',
    meta: { title: '单据详情' },
    component: () => import('@/views/finance/income/financeBills/detail.vue'),
    name: 'financeBillsStatementDetail',
  },
  {
    path: '/incomeAnalysis',
    meta: { title: '收入解析' },
    component: () => import('@/views/finance/income/incomeAnalysis/index.vue'),
    name: 'incomeAnalysis',
  },
  {
    path: '/incomeStatement',
    meta: { title: 'ToC收入结算单' },
    component: () => import('@/views/finance/income/incomeStatement/index.vue'),
    name: 'incomeStatement',
  },
  {
    path: '/incomeStatementToB',
    meta: { title: 'ToB收入结算单' },
    component: () => import('@/views/finance/income/incomeStatementToB/index.vue'),
    name: 'incomeStatementToB',
  },
  {
    path: '/salesInvoice',
    meta: { title: '销售发票' },
    component: () => import('@/views/finance/income/salesInvoice/index.vue'),
    name: 'salesInvoice',
  },
  {
    path: '/financeCNBills',
    meta: { title: 'CN单' },
    component: () => import('@/views/finance/income/CNBills/index.vue'),
    name: 'financeCNBills',
  },
  {
    path: '/financeWriteOff',
    meta: { title: '核销' },
    component: () => import('@/views/finance/income/CNBills/detail.vue'),
    name: 'financeWriteOff',
  },
  {
    path: '/receivableAccountCollect',
    meta: { title: '应收账龄汇总表' },
    component: () => import('@/views/finance/income/receivableAccountCollect/index.vue'),
    name: 'receivableAccountCollect',
  },
  {
    path: '/receivableAccountDetails',
    meta: { title: '应收账龄明细表' },
    component: () => import('@/views/finance/income/receivableAccountDetails/index.vue'),
    name: 'receivableAccountDetails',
  },
  {
    path: '/finance/budgetControlRules',
    meta: { title: '预算规则设置' },
    component: () => import('@/views/finance/costControl/controlRules/index.vue'),
    name: 'budgetControlRules',
  },
  {
    path: '/finance/budgetDataManagement',
    meta: { title: '预算池管理' },
    component: () => import('@/views/finance/costControl/budgetDataManagement/index.vue'),
    name: 'budgetDataManagement',
  },
  {
    path: '/finance/budgetExecuteTable',
    meta: { title: '预算执行单据' },
    component: () => import('@/views/finance/costControl/budgetExecuteTable/index.vue'),
    name: 'budgetExecuteTable',
  },
  {
    path: '/finance/budgetAdjustTable',
    meta: { title: '预算调整单' },
    component: () => import('@/views/finance/costControl/budgetAdjustTable/index.vue'),
    name: 'budgetAdjustTable',
  },
  {
    path: '/finance/pushMonitor',
    meta: { title: '推单监控平台', menuPath: ['集成平台', '财务系统'] },
    component: () => import('@/views/finance/pushMonitor/index.vue'),
    name: 'financePushMonitor',
  },
  {
    path: '/finance/expenseControlPayManage',
    meta: { title: '费控支付管理' },
    component: () => import('@/views/finance/costControl/payManage/index.vue'),
    name: 'expenseControlPayManage',
  },
];
