export default [
  {
    path: '/crm-app/community/:pathMatch(.*)*',
    meta: { title: '社群分析', code: 'community', initUrl: '/ai/dashboard', targets: ['社群分析'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-community',
  },
  {
    path: '/crm-app/home/:pathMatch(.*)*',
    meta: { title: '首页', code: 'home', initUrl: '/home', isFull: true, targets: ['首页'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-home',
  },
  {
    path: '/crm-app/downloadTask/:pathMatch(.*)*',
    meta: {
      title: '上传下载中心',
      code: 'downloadTask',
      initUrl: '/downloadTask',
      isFull: true,
      targets: ['上传下载中心'],
    },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-downloadTask',
  },
  {
    path: '/crm-app/capital/:pathMatch(.*)*',
    meta: { title: '用户资产', code: 'capital', initUrl: '/userList', targets: ['用户资产'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-capital',
  },
  {
    path: '/crm-app/member/:pathMatch(.*)*',
    meta: { title: '会员运营', code: 'member', initUrl: '/task-management', targets: ['会员运营'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-member',
  },
  {
    path: '/crm-app/marketingCampaign/:pathMatch(.*)*',
    meta: {
      title: '营销中台',
      code: 'marketingCampaign',
      initUrl: '/submissionActivity',
      targets: ['营销中台', '营销活动'],
    },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-marketingCampaign',
  },
  {
    path: '/crm-app/data/:pathMatch(.*)*',
    meta: { title: '数据', code: 'data', initUrl: '/pointRedemption', targets: ['数据'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-data',
  },
  {
    path: '/crm-app/station/:pathMatch(.*)*',
    meta: { title: '独立站', code: 'station', initUrl: '/couponConfig', targets: ['独立站'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-station',
  },
  {
    path: '/crm-app/lapp/:pathMatch(.*)*',
    meta: { title: 'APP', code: 'lapp', initUrl: '/marketingPush', targets: ['APP'] },
    component: () => import('@/views/system/crm-app/index.vue'),
    name: 'app:crm-lapp',
  },
  {
    path: '/kol-app/home/:pathMatch(.*)*',
    meta: { title: '首页', code: 'home', initUrl: '/personalcenter', targets: ['首页'] },
    component: () => import('@/views/system/kol-app/index.vue'),
    name: 'app:kol-home',
  },
  // 广告系统 未来需要做单个路由适配 todo
  {
    path: '/ad-app/home/:pathMatch(.*)*',
    meta: { title: '广告首页', code: 'home', initUrl: '/', isFull: true },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-system',
  },
  {
    path: '/ad-app/authManage/:pathMatch(.*)*',
    meta: { title: '授权管理', code: 'authManage', initUrl: '/authManage', isFull: true },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-authManage',
  },
  {
    path: '/ad-app/accountList/:pathMatch(.*)*',
    meta: { title: '账户列表', code: 'accountList', initUrl: '/accountList', isFull: true },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-accountList',
  },
  {
    path: '/ad-app/amzSpuMapping/:pathMatch(.*)*',
    meta: {
      title: 'AMZ广告SPU映射',
      code: 'amzSpuMapping',
      initUrl: '/amz-ad-spu-mapping',
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-amzSpuMapping',
  },
  {
    path: '/ad-app/amazonAd/:pathMatch(.*)*',
    meta: {
      title: '亚马逊广告',
      code: 'amazonAd',
      initUrl: '',
      isIframe: true,
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-amazonAd',
  },
  {
    path: '/ad-app/metaAd/:pathMatch(.*)*',
    meta: {
      title: 'Meta广告报告',
      code: 'metaAd',
      initUrl: '',
      isIframe: true,
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-metaAd',
  },
  {
    path: '/ad-app/resourceLibrary/:pathMatch(.*)*',
    meta: {
      title: '素材库',
      code: 'resourceLibrary',
      initUrl: '/resourceLibrary',
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-resourceLibrary',
  },
  {
    path: '/ad-app/adDelivery/:pathMatch(.*)*',
    meta: {
      title: '广告投放',
      code: 'adDelivery',
      initUrl: '/adDelivery',
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-adDelivery',
  },
  {
    path: '/ad-app/adLabel/:pathMatch(.*)*',
    meta: {
      title: '广告标签',
      code: 'adLabel',
      initUrl: '/adLabel',
      isFull: true,
    },
    component: () => import('@/views/system/ad-app/index.vue'),
    name: 'app:ad-adLabel',
  },
  // KMS 文档系统
  {
    path: '/kms-app/doc',
    meta: { title: '文档管理', initUrl: '/doc-redirect', code: 'doc', isFull: true },
    component: () => import('@/views/system/kms-app/index.vue'),
    name: 'app:kms-doc',
  },
  {
    path: '/kms-app/label',
    meta: { title: '标签管理', initUrl: '/label-redirect', code: 'label', isFull: true },
    component: () => import('@/views/system/kms-app/index.vue'),
    name: 'app:kms-label',
  },
  {
    path: '/cms-app/material',
    meta: { title: '素材中心', code: 'material', initUrl: '/materialcenter/index', isFull: true },
    component: () => import('@/views/system/cms-app/index.vue'),
    name: 'app:cms-material',
  },
  {
    path: '/cms-app/knowledge',
    meta: {
      title: '知识库',
      code: 'knowledge',
      initUrl: '/materialcenter/knowledge',
      isFull: true,
    },
    component: () => import('@/views/system/cms-app/index.vue'),
    name: 'app:cms-knowledge',
  },
  {
    path: '/cms-app/myfile',
    meta: { title: '我的文件', code: 'myfile', initUrl: '/materialcenter/myFile', isFull: true },
    component: () => import('@/views/system/cms-app/index.vue'),
    name: 'app:cms-myfile',
  },
];
