export enum refreshType {
  产品信息 = 'syncBudgetSku',
  售价信息 = 'syncBudgetMsrpPrice',
  采购成本价 = 'syncBudgetPurchaseCostPrice',
  研发项目 = 'syncBudgetNewProduct',
  国家信息 = 'syncBudgetCountry',
  渠道 = 'syncBudgetChannel',
  汇率信息 = 'syncBudgetCurrency',
  运营人员信息 = 'syncBudgetOperatorInfo',
  sku开卖时间 = 'syncSkuSaleDate',
  GTM品线 = 'syncGtmPl',
  员工 = 'syncMemberData',
  部门 = 'syncDeptData',
  映射关系 = 'syncCustomerData',
  收入结算单 = 'income_statement_order',
  ToB收入结算单 = 'settlement_form_data',
  平台库存单 = 'inventory_report_order',
  收款单 = 'income_payment_confirmation_order',
  OA付款单 = 'syncOaPaymentOrder',
  其他往来单位 = 'other_business_partners_refresh',
  银行账号 = 'syncBankAccount',
}
