export const logisticsChannelEnum = [
  { label: '海运加班船卡派', value: '海运加班船卡派' },
  { label: '海运加班船快递派', value: '海运加班船快递派' },
  { label: '每运快船', value: '每运快船' },
  { label: '每运快船卡派', value: '每运快船卡派' },
  { label: '海运快船快递派', value: '海运快船快递派' },
  { label: '海运普船', value: '海运普船' },
  { label: '海运普船卡派', value: '海运普船卡派' },
  { label: '海运普船快递派', value: '海运普船快递派' },
  { label: '卡航', value: '卡航' },
  { label: '卡航卡派', value: '卡航卡派' },
  { label: '卡航快递派', value: '卡航快递派' },
  { label: '空派', value: '空派' },
  { label: '空运卡派', value: '空运卡派' },
  { label: '空运快递派', value: '空运快递派' },
  { label: '快递', value: '快递' },
];

export const productTypes = [
  { label: '带电带磁', prop: 'batteryFee' },
  { label: '木制品', prop: 'woodenFee' },
  { label: '纺织品', prop: 'textileFee' },
  { label: '皮具', prop: 'leatherFee' },
  { label: '粉末', prop: 'powderFee' },
  { label: '食品', prop: 'foodFee' },
  { label: '纯液体', prop: 'pureLiquidFee' },
  { label: '带液体', prop: 'liquidFee' },
  { label: '危险品', prop: 'dangerousFee' },
  { label: '膏体', prop: 'pasteFee' },
  { label: '敏感货', prop: 'sensitiveFee' },
  { label: '化妆品', prop: 'cosmeticFee' },
  { label: '贴标费', prop: 'labelFee' },
  { label: '预留字段1', prop: 'reservedOneFee' },
  { label: '预留字段2', prop: 'reservedTwoFee' },
];
